# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NNCoins' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for NNCoins
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  pod 'React', :subspecs => [
  'Core',
  'tvOS',
  'RCTImage',
  'RCTNetwork',
  'RCTPushNotification',
  'RCTText',
  'DevSupport',
  'BatchedBridge'
  ], :path => '../node_modules/react-native'

  pod 'react-native-smooch', :path => '../node_modules/react-native-smooch'
  
  pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'
  
  pod 'Firebase/Core'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if target.name == 'yoga'
#            target.build_configurations.each do |config|
#                config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
#                config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
#            end
#        if target.name == "React"
#                target.remove_from_project
#            end
#        end
#    end
#end
