export const FETCHING_PRICE_DATA = 'FETCHING_PRICE_DATA';
export const FETCHING_PRICE_DATA_SUCCESS = 'FETCHING_PRICE_DATA_SUCCESS';
export const FETCHING_PRICE_DATA_FAIL = 'FETCHING_PRICE_DATA_FAIL';

export const FETCHING_COIN_LIST = 'FETCHING_COIN_LIST';
export const FETCHING_COIN_LIST_SUCCESS = 'FETCHING_COIN_LIST_SUCCESS';
export const FETCHING_COIN_LIST_FAIL = 'FETCHING_COIN_LIST_FAIL';

export const FETCHING_COIN_BY_ID = 'FETCHING_COIN_BY_ID';
export const FETCHING_COIN_BY_ID_SUCCESS = 'FETCHING_COIN_BY_ID_SUCCESS';
export const FETCHING_COIN_BY_ID_FAIL = 'FETCHING_COIN_BY_ID_FAIL';

export const CACHE_COIN_LIST = 'CACHE_COIN_LIST';
export const CACHE_COIN_LIST_SUCCESS = 'CACHE_COIN_LIST_SUCCESS';

export const SET_COIN_SEARCH_INPUT = 'SET_COIN_SEARCH_INPUT';


export const GET_CACHED_COIN_LIST = 'GET_CACHED_COIN_LIST';
export const GET_CACHED_COIN_LIST_SUCCESS = 'GET_CACHED_COIN_LIST_SUCCESS';

export const FETCHING_NEWS_LIST = 'FETCHING_NEWS_LIST';
export const FETCHING_NEWS_LIST_SUCCESS = 'FETCHING_NEWS_LIST_SUCCESS';
export const FETCHING_NEWS_LIST_FAIL = 'FETCHING_NEW_LIST_FAIL';
export const VIEWABLE_NEWS_ITEMS_CHANGED = 'VIEWABLE_NEWS_ITEMS_CHANGED';
export const CHECK_IF_VIEWABLE = 'CHECK_IF_VIEWABLE';

export const FETCHING_WEEKLY_UPDATE_VIDEO = 'FETCHING_WEEKLY_UPDATE_VIDEO';
export const FETCHING_WEEKLY_UPDATE_VIDEO_SUCCESS = 'FETCHING_WEEKLY_UPDATE_VIDEO_SUCCESS';
export const FETCHING_WEEKLY_UPDATE_VIDEO_FAIL = 'FETCHING_WEEKLY_UPDATE_VIDEO_FAIL';


export const FETCHING_LESSONS = 'FETCHING_LESSONS';
export const FETCHING_LESSONS_SUCCESS = 'FETCHING_LESSONS_SUCCESS';
export const FETCHING_LESSONS_FAIL = 'FETCHING_LESSONS_FAIL';
export const SELECT_LESSON = 'SELECT_LESSON';
export const FETCHING_LESSONS_DURATION = 'FETCHING_LESSONS_DURATION';
export const FETCHING_LESSONS_DURATION_SUCCESS = 'FETCHING_LESSONS_DURATION_SUCCESS';
export const FETCHING_LESSONS_DURATION_FAIL = 'FETCHING_LESSONS_DURATION_FAIL';




export const CHAT_BUTTON_TAPPED = 'CHAT_BUTTON_TAPPED';
export const OPEN_CHAT_WINDOW = 'OPEN_CHAT_WINDOW';
export const OPEN_CHAT_FORM = 'OPEN_CHAT_FORM';
export const CLOSE_CHAT_FORM = 'CLOSE_CHAT_FORM';
export const GET_UNREAD_COUNT = 'GET_UNREAD_COUNT';
export const GET_UNREAD_COUNT_SUCCESS = 'GET_UNREAD_COUNT_SUCCESS';
export const SET_NICK_NAME = 'SET_NICK_NAME';
export const SAVE_NICNAME_SET = 'SAVE_NICNAME_SET';
export const SAVE_NICNAME_SET_SUCCESS = 'SAVE_NICNAME_SET_SUCCESS';
export const CHECK_IF_NAME_SET = 'CHECK_IF_NAME_SET';
export const CHECK_IF_NAME_SET_SUCCESS = 'CHECK_IF_NAME_SET_SUCCESS';

export const LOADING_CHART_PRICES = 'LOADING_CHART_PRICES';
export const LOADING_CHART_PRICES_SUCCESS = 'LOADING_CHART_PRICES_SUCCESS';
export const LOADING_CHART_PRICES_FAIL = 'LOADING_CHART_PRICES_FAIL';


export const SELECTED_CHART_RANGE = 'SELECTED_CHART_RANGE';
export const SELECTED_CURRENT_COIN = 'SELECTED_CURRENT_COIN';

export const SELECTED_TARGET_CURRENCY = 'SELECTED_TARGET_CURRENCY';
