export const FETCHING_PRICE_DATA = 'FETCHING_PRICE_DATA';
export const FETCHING_PRICE_DATA_SUCCESS = 'FETCHING_PRICE_DATA_SUCCESS';
export const FETCHING_PRICE_DATA_FAIL = 'FETCHING_PRICE_DATA_FAIL';

export const FETCHING_COIN_LIST = 'FETCHING_COIN_LIST';
export const FETCHING_COIN_LIST_SUCCESS = 'FETCHING_COIN_LIST_SUCCESS';
export const FETCHING_COIN_LIST_FAIL = 'FETCHING_COIN_LIST_FAIL';

export const FETCHING_COIN_BY_ID = 'FETCHING_COIN_BY_ID';
export const FETCHING_COIN_BY_ID_SUCCESS = 'FETCHING_COIN_BY_ID_SUCCESS';
export const FETCHING_COIN_BY_ID_FAIL = 'FETCHING_COIN_BY_ID_FAIL';

export const CACHE_COIN_LIST = 'CACHE_COIN_LIST';
export const CACHE_COIN_LIST_SUCCESS = 'CACHE_COIN_LIST_SUCCESS';

export const GET_CACHED_COIN_LIST = 'GET_CACHED_COIN_LIST';
export const GET_CACHED_COIN_LIST_SUCCESS = 'GET_CACHED_COIN_LIST_SUCCESS';

export const FETCHING_NEWS_LIST = 'FETCHING_NEWS_LIST';
export const FETCHING_NEWS_LIST_SUCCESS = 'FETCHING_NEWS_LIST_SUCCESS';
export const FETCHING_NEWS_LIST_FAIL = 'FETCHING_NEW_LIST_FAIL';
export const VIEWABLE_NEWS_ITEMS_CHANGED = 'VIEWABLE_NEWS_ITEMS_CHANGED';
export const CHECK_IF_VIEWABLE = 'CHECK_IF_VIEWABLE';

export const FETCHING_WEEKLY_UPDATE_VIDEO = 'FETCHING_WEEKLY_UPDATE_VIDEO';
export const FETCHING_WEEKLY_UPDATE_VIDEO_SUCCESS = 'FETCHING_WEEKLY_UPDATE_VIDEO_SUCCESS';
export const FETCHING_WEEKLY_UPDATE_VIDEO_FAIL = 'FETCHING_WEEKLY_UPDATE_VIDEO_FAIL';


export const CHAT_BUTTON_TAPPED = 'CHAT_BUTTON_TAPPED';
export const OPEN_CHAT_WINDOW = 'OPEN_CHAT_WINDOW';
export const OPEN_CHAT_FORM = 'OPEN_CHAT_FORM';
export const CLOSE_CHAT_FORM = 'CLOSE_CHAT_FORM';
export const GET_UNREAD_COUNT = 'GET_UNREAD_COUNT';
export const GET_UNREAD_COUNT_SUCCESS = 'GET_UNREAD_COUNT_SUCCESS';
export const SET_NICK_NAME = 'SET_NICK_NAME';
export const SAVE_NICNAME_SET = 'SAVE_NICNAME_SET';
export const SAVE_NICNAME_SET_SUCCESS = 'SAVE_NICNAME_SET_SUCCESS';
export const CHECK_IF_NAME_SET = 'CHECK_IF_NAME_SET';
export const CHECK_IF_NAME_SET_SUCCESS = 'CHECK_IF_NAME_SET_SUCCESS';


