export const FETCHING_PRICE_DATA = 'FETCHING_PRICE_DATA';
export const FETCHING_PRICE_DATA_SUCCESS = 'FETCHING_PRICE_DATA_SUCCESS';
export const FETCHING_PRICE_DATA_FAIL = 'FETCHING_PRICE_DATA_FAIL';

export const FETCHING_COIN_LIST = 'FETCHING_COIN_LIST';
export const FETCHING_COIN_LIST_SUCCESS = 'FETCHING_COIN_LIST_SUCCESS';
export const FETCHING_COIN_LIST_FAIL = 'FETCHING_COIN_LIST_FAIL';

export const FETCHING_NEWS_LIST = 'FETCHING_NEWS_LIST';
export const FETCHING_NEWS_LIST_SUCCESS = 'FETCHING_NEWS_LIST_SUCCESS';
export const FETCHING_NEWS_LIST_FAIL = 'FETCHING_NEW_LIST_FAIL';


export const CHAT_BUTTON_TAPPED = 'CHAT_BUTTON_TAPPED';
export const GET_UNREAD_COUNT = 'GET_UNREAD_COUNT';
export const GET_UNREAD_COUNT_SUCCESS = 'GET_UNREAD_COUNT_SUCCESS';


